/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obe.matriks;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author adam
 */
public class menghitungMatrix extends javax.swing.JFrame {

    /**
     * Creates new form menghitungMatrix
     */
    // instance
    private double matrixB[][] = new double[3][3];
    private double matrixA[][] = new double[3][3];
    private double matrixhasil[][] = new double[3][3];

    private int n;

    public menghitungMatrix() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(tambah);
        bg.add(kurang);
        bg.add(kali);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField18 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        b1k1b = new javax.swing.JTextField();
        b1k2b = new javax.swing.JTextField();
        b2k1b = new javax.swing.JTextField();
        b2k2b = new javax.swing.JTextField();
        b3k2b = new javax.swing.JTextField();
        b3k1b = new javax.swing.JTextField();
        TB = new javax.swing.JButton();
        b1k3b = new javax.swing.JTextField();
        b2k3b = new javax.swing.JTextField();
        b3k3b = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        b1k1a = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        b1k2a = new javax.swing.JTextField();
        b2k1a = new javax.swing.JTextField();
        b2k2a = new javax.swing.JTextField();
        TA = new javax.swing.JButton();
        b1k3a = new javax.swing.JTextField();
        b2k3a = new javax.swing.JTextField();
        b3k1a = new javax.swing.JTextField();
        b3k2a = new javax.swing.JTextField();
        b3k3a = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        b1k1hasil = new javax.swing.JTextField();
        b1k2hasil = new javax.swing.JTextField();
        b2k1hasil = new javax.swing.JTextField();
        b2k2hasil = new javax.swing.JTextField();
        b3k1hasil = new javax.swing.JTextField();
        b3k2hasil = new javax.swing.JTextField();
        b3k3hasil = new javax.swing.JTextField();
        b1k3hasil = new javax.swing.JTextField();
        b2k3hasil = new javax.swing.JTextField();
        Thasil = new javax.swing.JButton();
        tambah = new javax.swing.JRadioButton();
        kurang = new javax.swing.JRadioButton();
        kali = new javax.swing.JRadioButton();
        hasil = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menghitung Matrix");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Norasi", 0, 24)); // NOI18N
        jLabel1.setText("Matrix Calculate");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obe/matriks/Gambar/panah.jpg"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Matrix 1");

        b1k1b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k1b.setText("0.0");
        b1k1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k1bActionPerformed(evt);
            }
        });

        b1k2b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k2b.setText("0.0");
        b1k2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k2bActionPerformed(evt);
            }
        });

        b2k1b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k1b.setText("0.0");
        b2k1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k1bActionPerformed(evt);
            }
        });

        b2k2b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k2b.setText("0.0");
        b2k2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k2bActionPerformed(evt);
            }
        });

        b3k2b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k2b.setText("0.0");
        b3k2b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k2bActionPerformed(evt);
            }
        });

        b3k1b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k1b.setText("0.0");
        b3k1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k1bActionPerformed(evt);
            }
        });

        TB.setText("Transpose");
        TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBActionPerformed(evt);
            }
        });

        b1k3b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k3b.setText("0.0");
        b1k3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k3bActionPerformed(evt);
            }
        });

        b2k3b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k3b.setText("0.0");
        b2k3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k3bActionPerformed(evt);
            }
        });

        b3k3b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k3b.setText("0.0");
        b3k3b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k3bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(b2k1b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b2k2b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b2k3b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(b3k1b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b3k2b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b3k3b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(b1k1b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b1k2b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(b1k3b, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TB)
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1k1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2k2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b2k1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b2k3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b3k1b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b3k2b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(b3k3b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(TB)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b1k1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k1a.setText("0.0");
        b1k1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k1aActionPerformed(evt);
            }
        });

        jLabel2.setText("Matrix 2");

        b1k2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k2a.setText("0.0");
        b1k2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k2aActionPerformed(evt);
            }
        });

        b2k1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k1a.setText("0.0");
        b2k1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k1aActionPerformed(evt);
            }
        });

        b2k2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k2a.setText("0.0");
        b2k2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k2aActionPerformed(evt);
            }
        });

        TA.setText("Transpose");
        TA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAActionPerformed(evt);
            }
        });

        b1k3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k3a.setText("0.0");
        b1k3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k3aActionPerformed(evt);
            }
        });

        b2k3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k3a.setText("0.0");
        b2k3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k3aActionPerformed(evt);
            }
        });

        b3k1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k1a.setText("0.0");
        b3k1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k1aActionPerformed(evt);
            }
        });

        b3k2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k2a.setText("0.0");
        b3k2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k2aActionPerformed(evt);
            }
        });

        b3k3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k3a.setText("0.0");
        b3k3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k3aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b3k1a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b3k2a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b3k3a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b2k1a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b2k2a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b2k3a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(b1k1a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b1k2a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b1k3a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(TA)
                        .addGap(59, 59, 59))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1k1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2k1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3k1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(TA)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Result");

        b1k1hasil.setEditable(false);
        b1k1hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k1hasilActionPerformed(evt);
            }
        });

        b1k2hasil.setEditable(false);
        b1k2hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k2hasilActionPerformed(evt);
            }
        });

        b2k1hasil.setEditable(false);
        b2k1hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k1hasilActionPerformed(evt);
            }
        });

        b2k2hasil.setEditable(false);
        b2k2hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k2hasilActionPerformed(evt);
            }
        });

        b3k1hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k1hasilActionPerformed(evt);
            }
        });

        b3k2hasil.setEditable(false);
        b3k2hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k2hasilActionPerformed(evt);
            }
        });

        b3k3hasil.setEditable(false);
        b3k3hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k3hasilActionPerformed(evt);
            }
        });

        b1k3hasil.setEditable(false);
        b1k3hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k3hasilActionPerformed(evt);
            }
        });

        b2k3hasil.setEditable(false);
        b2k3hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k3hasilActionPerformed(evt);
            }
        });

        Thasil.setText("Transpose");
        Thasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(b2k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b3k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(b1k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(b2k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b2k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(b3k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b3k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b1k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(b1k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Thasil)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Thasil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tambah.setText("increase");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        kurang.setText("subtraction");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });

        kali.setText("multiplication");

        hasil.setBackground(new java.awt.Color(153, 153, 255));
        hasil.setFont(new java.awt.Font("Liberation Sans", 0, 38)); // NOI18N
        hasil.setText("=");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose with calculate :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(372, 372, 372))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tambah)
                                        .addGap(20, 20, 20)
                                        .addComponent(kurang)
                                        .addGap(18, 18, 18)
                                        .addComponent(kali))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(hasil))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(kurang)
                            .addComponent(kali))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hasil)
                        .addGap(31, 31, 31)))
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b1k1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k1aActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void b1k2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k2aActionPerformed

    private void b2k1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k1aActionPerformed

    private void b2k2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k2aActionPerformed

    private void b1k2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k2bActionPerformed

    private void b2k1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k1bActionPerformed

    private void b2k2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k2bActionPerformed

    private void b3k2bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k2bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k2bActionPerformed

    private void b3k1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k1bActionPerformed

    private void b1k1hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k1hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k1hasilActionPerformed

    private void b1k2hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k2hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k2hasilActionPerformed

    private void b2k1hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k1hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k1hasilActionPerformed

    private void b2k2hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k2hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k2hasilActionPerformed

    private void b3k1hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k1hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k1hasilActionPerformed

    private void b3k2hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k2hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k2hasilActionPerformed

    private void b1k3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k3bActionPerformed

    private void b2k3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k3bActionPerformed

    private void b3k3bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k3bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k3bActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kurangActionPerformed

    private void b3k3hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k3hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k3hasilActionPerformed

    private void b1k3hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k3hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k3hasilActionPerformed

    private void b2k3hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k3hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k3hasilActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        // instance
        try {
            JOptionPane.showConfirmDialog(null, "Ordo pertambahan dan pengurangan harus sama", "hasil", JOptionPane.OK_OPTION);

            matrixtampilA();
            matrixtampilB();

            //statement tambah
            if (tambah.isSelected()) {
                //perulangan untuk menghitung panjang per baris dan kolom         
                hasiltambah();
                tampilhasil();

            } else if (kurang.isSelected()) {
                //perulangan untuk menghitung panjang per baris dan kolom
                hasilkurang();
                tampilhasil();
            } else if (kali.isSelected()) {
                hasikali();
                tampilhasil();

            }
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Yang anda inputkan kosong atau bukan angka", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_hasilActionPerformed

    private void TAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAActionPerformed
        // TODO add your handling code here:
        try {
            matrixtampilA();
            double tranpose[][] = new double[3][3];
            for (int i = 0; i < matrixA.length; i++) {
                for (int j = 0; j < matrixA[0].length; j++) {
                    tranpose[j][i] = matrixA[i][j];
                }
            }
            b1k1a.setText(String.valueOf(tranpose[0][0]));
            b1k2a.setText(String.valueOf(tranpose[0][1]));
            b1k3a.setText(String.valueOf(tranpose[0][2]));
            b2k1a.setText(String.valueOf(tranpose[1][0]));
            b2k2a.setText(String.valueOf(tranpose[1][1]));
            b2k3a.setText(String.valueOf(tranpose[1][2]));
            b3k1a.setText(String.valueOf(tranpose[2][0]));
            b3k2a.setText(String.valueOf(tranpose[2][1]));
            b3k3a.setText(String.valueOf(tranpose[2][2]));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Yang anda inputkan kosong atau bukan angka", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_TAActionPerformed

    private void TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBActionPerformed
        // TODO add your handling code here:
        try {
            matrixtampilB();
            double tranpose[][] = new double[3][3];
            for (int i = 0; i < matrixB.length; i++) {
                for (int j = 0; j < matrixB[0].length; j++) {
                    tranpose[j][i] = matrixB[i][j];
                }
            }
            b1k1b.setText(String.valueOf(tranpose[0][0]));
            b1k2b.setText(String.valueOf(tranpose[0][1]));
            b1k3b.setText(String.valueOf(tranpose[0][2]));
            b2k1b.setText(String.valueOf(tranpose[1][0]));
            b2k2b.setText(String.valueOf(tranpose[1][1]));
            b2k3b.setText(String.valueOf(tranpose[1][2]));
            b3k1b.setText(String.valueOf(tranpose[2][0]));
            b3k2b.setText(String.valueOf(tranpose[2][1]));
            b3k3b.setText(String.valueOf(tranpose[2][2]));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Yang anda inputkan kosong atau bukan angka", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_TBActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void b1k3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k3aActionPerformed

    private void b2k3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k3aActionPerformed

    private void b3k1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k1aActionPerformed

    private void b3k2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k2aActionPerformed

    private void b3k3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k3aActionPerformed

    private void ThasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThasilActionPerformed
        // TODO add your handling code here:
        try {
            gethasil();
            double tranpose[][] = new double[3][3];
            for (int i = 0; i < matrixhasil.length; i++) {
                for (int j = 0; j < matrixhasil[0].length; j++) {
                    tranpose[j][i] = matrixhasil[i][j];
                }
            }
            b1k1hasil.setText(String.valueOf(tranpose[0][0]));
            b1k2hasil.setText(String.valueOf(tranpose[0][1]));
            b1k3hasil.setText(String.valueOf(tranpose[0][2]));
            b2k1hasil.setText(String.valueOf(tranpose[1][0]));
            b2k2hasil.setText(String.valueOf(tranpose[1][1]));
            b2k3hasil.setText(String.valueOf(tranpose[1][2]));
            b3k1hasil.setText(String.valueOf(tranpose[2][0]));
            b3k2hasil.setText(String.valueOf(tranpose[2][1]));
            b3k3hasil.setText(String.valueOf(tranpose[2][2]));

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Yang anda inputkan kosong atau bukan angka", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        }

    }//GEN-LAST:event_ThasilActionPerformed

    private void b1k1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k1bActionPerformed

    public void matrixtampilA() {
        matrixA[0][0] = Double.parseDouble(b1k1a.getText());
        matrixA[0][1] = Double.parseDouble(b1k2a.getText());
        matrixA[0][2] = Double.parseDouble(b1k3a.getText());
        matrixA[1][0] = Double.parseDouble(b2k1a.getText());
        matrixA[1][1] = Double.parseDouble(b2k2a.getText());
        matrixA[1][2] = Double.parseDouble(b2k3a.getText());
        matrixA[2][0] = Double.parseDouble(b3k1a.getText());
        matrixA[2][1] = Double.parseDouble(b3k2a.getText());
        matrixA[2][2] = Double.parseDouble(b3k3a.getText());
    }

    public void matrixtampilB() {
        matrixB[0][0] = Double.parseDouble(b1k1b.getText());
        matrixB[0][1] = Double.parseDouble(b1k2b.getText());
        matrixB[0][2] = Double.parseDouble(b1k3b.getText());
        matrixB[1][0] = Double.parseDouble(b2k1b.getText());
        matrixB[1][1] = Double.parseDouble(b2k2b.getText());
        matrixB[1][2] = Double.parseDouble(b2k3b.getText());
        matrixB[2][0] = Double.parseDouble(b3k1b.getText());
        matrixB[2][1] = Double.parseDouble(b3k2b.getText());
        matrixB[2][2] = Double.parseDouble(b3k3b.getText());

    }

    public void hasiltambah() {
        for (int i = 0; i < matrixB.length; i++) {
            for (int j = 0; j < matrixB[0].length; j++) {
                matrixhasil[i][j] = matrixB[i][j] + matrixA[i][j];
            }
        }
    }

    public void hasilkurang() {
        for (int i = 0; i < matrixB.length; i++) {
            for (int j = 0; j < matrixB[0].length; j++) {
                matrixhasil[i][j] = matrixB[i][j] - matrixA[i][j];
            }
        }

    }

    public void hasikali() {
        //b1k1
        matrixhasil[0][0] = (matrixB[0][0] * matrixA[0][0]) + (matrixB[0][1] * matrixA[1][0]) + (matrixB[0][2] * matrixA[2][0]);
        //b1k2
        matrixhasil[0][1] = (matrixB[0][0] * matrixA[0][1]) + (matrixB[0][1] * matrixA[1][1]) + (matrixB[0][2] * matrixA[2][1]);
        //b1k3
        matrixhasil[0][2] = (matrixB[0][0] * matrixA[0][2]) + (matrixB[0][1] * matrixA[1][2]) + (matrixB[0][2] * matrixA[2][2]);

        //b2k1
        matrixhasil[1][0] = (matrixB[1][0] * matrixA[0][0]) + (matrixB[1][1] * matrixA[1][0]) + (matrixB[1][2] * matrixA[2][0]);
        //b2k2
        matrixhasil[1][1] = (matrixB[1][0] * matrixA[0][1]) + (matrixB[1][1] * matrixA[1][1]) + (matrixB[1][2] * matrixA[2][1]);
        //b2k3
        matrixhasil[1][2] = (matrixB[1][0] * matrixA[0][2]) + (matrixB[1][1] * matrixA[1][2]) + (matrixB[1][2] * matrixA[2][2]);

        //b3k1
        matrixhasil[2][0] = (matrixB[2][0] * matrixA[0][0]) + (matrixB[2][1] * matrixA[1][0]) + (matrixB[2][2] * matrixA[2][0]);
        //b3k2
        matrixhasil[2][1] = (matrixB[2][0] * matrixA[0][1]) + (matrixB[2][1] * matrixA[1][1]) + (matrixB[2][2] * matrixA[2][1]);
        //b3k3
        matrixhasil[2][2] = (matrixB[2][0] * matrixA[0][2]) + (matrixB[2][1] * matrixA[1][2]) + (matrixB[2][2] * matrixA[2][2]);

    }

    public void gethasil() {
        matrixhasil[0][0] = Double.parseDouble(b1k1hasil.getText());
        matrixhasil[0][1] = Double.parseDouble(b1k2hasil.getText());
        matrixhasil[0][2] = Double.parseDouble(b1k3hasil.getText());
        matrixhasil[1][0] = Double.parseDouble(b2k1hasil.getText());
        matrixhasil[1][1] = Double.parseDouble(b2k2hasil.getText());
        matrixhasil[1][2] = Double.parseDouble(b2k3hasil.getText());
        matrixhasil[2][0] = Double.parseDouble(b3k1hasil.getText());
        matrixhasil[2][1] = Double.parseDouble(b3k2hasil.getText());
        matrixhasil[2][2] = Double.parseDouble(b3k3hasil.getText());
    }

    public void tampilhasil() {
        // menampilkan ke hasil
        b1k1hasil.setText(String.valueOf(matrixhasil[0][0]));
        b1k2hasil.setText(String.valueOf(matrixhasil[0][1]));
        b1k3hasil.setText(String.valueOf(matrixhasil[0][2]));
        b2k1hasil.setText(String.valueOf(matrixhasil[1][0]));
        b2k2hasil.setText(String.valueOf(matrixhasil[1][1]));
        b2k3hasil.setText(String.valueOf(matrixhasil[1][2]));
        b3k1hasil.setText(String.valueOf(matrixhasil[2][0]));
        b3k2hasil.setText(String.valueOf(matrixhasil[2][1]));
        b3k3hasil.setText(String.valueOf(matrixhasil[2][2]));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menghitungMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menghitungMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menghitungMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menghitungMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menghitungMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TA;
    private javax.swing.JButton TB;
    private javax.swing.JButton Thasil;
    private javax.swing.JTextField b1k1a;
    private javax.swing.JTextField b1k1b;
    private javax.swing.JTextField b1k1hasil;
    private javax.swing.JTextField b1k2a;
    private javax.swing.JTextField b1k2b;
    private javax.swing.JTextField b1k2hasil;
    private javax.swing.JTextField b1k3a;
    private javax.swing.JTextField b1k3b;
    private javax.swing.JTextField b1k3hasil;
    private javax.swing.JTextField b2k1a;
    private javax.swing.JTextField b2k1b;
    private javax.swing.JTextField b2k1hasil;
    private javax.swing.JTextField b2k2a;
    private javax.swing.JTextField b2k2b;
    private javax.swing.JTextField b2k2hasil;
    private javax.swing.JTextField b2k3a;
    private javax.swing.JTextField b2k3b;
    private javax.swing.JTextField b2k3hasil;
    private javax.swing.JTextField b3k1a;
    private javax.swing.JTextField b3k1b;
    private javax.swing.JTextField b3k1hasil;
    private javax.swing.JTextField b3k2a;
    private javax.swing.JTextField b3k2b;
    private javax.swing.JTextField b3k2hasil;
    private javax.swing.JTextField b3k3a;
    private javax.swing.JTextField b3k3b;
    private javax.swing.JTextField b3k3hasil;
    private javax.swing.JButton hasil;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JRadioButton kali;
    private javax.swing.JRadioButton kurang;
    private javax.swing.JRadioButton tambah;
    // End of variables declaration//GEN-END:variables
}
