/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obe.matriks;

import javax.swing.JOptionPane;
import org.apache.commons.math3.fraction.Fraction;

/**
 *
 * @author adam
 */
public class OBE extends javax.swing.JFrame {

    /**
     * Creates new form OBE
     */
    // instance
    double[][] matrixA = new double[3][3];
    double[][] minor = new double[3][3];
    double[][] kofaktor = new double[3][3];
    double[][] adjoin = new double[3][3];
    Fraction[][] pecahan = new Fraction[3][3];

    public OBE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        b1k1a = new javax.swing.JTextField();
        b2k1a = new javax.swing.JTextField();
        b1k2a = new javax.swing.JTextField();
        b1k3a = new javax.swing.JTextField();
        b2k3a = new javax.swing.JTextField();
        b2k2a = new javax.swing.JTextField();
        b3k1a = new javax.swing.JTextField();
        b3k2a = new javax.swing.JTextField();
        b3k3a = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        b1k1hasil = new javax.swing.JTextField();
        b1k2hasil = new javax.swing.JTextField();
        b1k3hasil = new javax.swing.JTextField();
        b2k1hasil = new javax.swing.JTextField();
        b2k2hasil = new javax.swing.JTextField();
        b3k1hasil = new javax.swing.JTextField();
        b2k3hasil = new javax.swing.JTextField();
        b3k2hasil = new javax.swing.JTextField();
        b3k3hasil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hasil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Invers");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b1k1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k1a.setText("0");
        b1k1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k1aActionPerformed(evt);
            }
        });

        b2k1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k1a.setText("0");
        b2k1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k1aActionPerformed(evt);
            }
        });

        b1k2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k2a.setText("0");
        b1k2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k2aActionPerformed(evt);
            }
        });

        b1k3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b1k3a.setText("0");
        b1k3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k3aActionPerformed(evt);
            }
        });

        b2k3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k3a.setText("0");
        b2k3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k3aActionPerformed(evt);
            }
        });

        b2k2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b2k2a.setText("0");
        b2k2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k2aActionPerformed(evt);
            }
        });

        b3k1a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k1a.setText("0");
        b3k1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k1aActionPerformed(evt);
            }
        });

        b3k2a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k2a.setText("0");
        b3k2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k2aActionPerformed(evt);
            }
        });

        b3k3a.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        b3k3a.setText("0");
        b3k3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k3aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b3k1a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k1a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k1a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b1k2a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b1k3a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b2k2a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b2k3a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b3k2a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(b3k3a, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1k1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2k1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3k1a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k2a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k3a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b1k1hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b1k1hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k1hasilActionPerformed(evt);
            }
        });

        b1k2hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b1k2hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k2hasilActionPerformed(evt);
            }
        });

        b1k3hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b1k3hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1k3hasilActionPerformed(evt);
            }
        });

        b2k1hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b2k1hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k1hasilActionPerformed(evt);
            }
        });

        b2k2hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b2k2hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k2hasilActionPerformed(evt);
            }
        });

        b3k1hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b3k1hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k1hasilActionPerformed(evt);
            }
        });

        b2k3hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b2k3hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2k3hasilActionPerformed(evt);
            }
        });

        b3k2hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b3k2hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k2hasilActionPerformed(evt);
            }
        });

        b3k3hasil.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        b3k3hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3k3hasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b3k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(b3k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b2k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b1k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b1k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b2k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3k1hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k2hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3k3hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        b1k1hasil.getAccessibleContext().setAccessibleName("");
        b1k2hasil.getAccessibleContext().setAccessibleName("");
        b1k3hasil.getAccessibleContext().setAccessibleName("");
        b2k1hasil.getAccessibleContext().setAccessibleName("");
        b2k2hasil.getAccessibleContext().setAccessibleName("");
        b3k1hasil.getAccessibleContext().setAccessibleName("");
        b2k3hasil.getAccessibleContext().setAccessibleName("");
        b3k2hasil.getAccessibleContext().setAccessibleName("");
        b3k3hasil.getAccessibleContext().setAccessibleName("");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Input");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Result");

        hasil.setBackground(new java.awt.Color(153, 153, 255));
        hasil.setFont(new java.awt.Font("Liberation Sans", 0, 30)); // NOI18N
        hasil.setText("=");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(hasil)
                .addGap(72, 72, 72)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(hasil)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Norasi", 0, 24)); // NOI18N
        jLabel2.setText("Invers Matrix");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obe/matriks/Gambar/panah.jpg"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton2)
                        .addGap(335, 335, 335)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b1k1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k1aActionPerformed

    private void b2k1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k1aActionPerformed

    private void b1k2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k2aActionPerformed

    private void b1k3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k3aActionPerformed

    private void b2k3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k3aActionPerformed

    private void b2k2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k2aActionPerformed

    private void b3k1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k1aActionPerformed

    private void b3k2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k2aActionPerformed

    private void b3k3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k3aActionPerformed

    private void b1k1hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k1hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k1hasilActionPerformed

    private void b1k2hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k2hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k2hasilActionPerformed

    private void b1k3hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1k3hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b1k3hasilActionPerformed

    private void b2k1hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k1hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k1hasilActionPerformed

    private void b2k2hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k2hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k2hasilActionPerformed

    private void b3k1hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k1hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k1hasilActionPerformed

    private void b2k3hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2k3hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b2k3hasilActionPerformed

    private void b3k2hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k2hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k2hasilActionPerformed

    private void b3k3hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3k3hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3k3hasilActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        adjoin();


    }//GEN-LAST:event_hasilActionPerformed

    private void Invers() {
        try {
            matrixA[0][0] = Double.parseDouble(b1k1a.getText());
            matrixA[0][1] = Double.parseDouble(b1k2a.getText());
            matrixA[0][2] = Double.parseDouble(b1k3a.getText());
            matrixA[1][0] = Double.parseDouble(b2k1a.getText());
            matrixA[1][1] = Double.parseDouble(b2k2a.getText());
            matrixA[1][2] = Double.parseDouble(b2k3a.getText());
            matrixA[2][0] = Double.parseDouble(b3k1a.getText());
            matrixA[2][1] = Double.parseDouble(b3k2a.getText());
            matrixA[2][2] = Double.parseDouble(b3k3a.getText());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "Yang anda inputkan kosong atau bukan angka", "Konfirmasi", JOptionPane.OK_OPTION);
        }
    }

    private double determinan() {
        Invers();
        double detp = ((matrixA[0][0] * matrixA[1][1] * matrixA[2][2]) + (matrixA[0][1] * matrixA[1][2] * matrixA[2][0]) + (matrixA[0][2] * matrixA[1][0] * matrixA[2][1])) - ((matrixA[2][0] * matrixA[1][1] * matrixA[0][2]) + (matrixA[2][1] * matrixA[1][2] * matrixA[0][0]) + (matrixA[2][2] * matrixA[1][0] * matrixA[0][1]));
        return detp;
    }

    private void Minor() {
        Invers();
        // Mb1k1
        minor[0][0] = (matrixA[1][1] * matrixA[2][2]) - (matrixA[1][2] * matrixA[2][1]);
        // mb1k2
        minor[0][1] = (matrixA[1][0] * matrixA[2][2]) - (matrixA[1][2] * matrixA[2][0]);
        // mb1k3
        minor[0][2] = (matrixA[1][0] * matrixA[2][1]) - (matrixA[1][1] * matrixA[2][0]);

        //mb2k1
        minor[1][0] = (matrixA[0][1] * matrixA[2][2]) - (matrixA[0][2] * matrixA[2][1]);
        //mb2k2
        minor[1][1] = (matrixA[0][0] * matrixA[2][2]) - (matrixA[0][2] * matrixA[2][0]);
        //mb2k3
        minor[1][2] = (matrixA[0][0] * matrixA[2][1]) - (matrixA[0][1] * matrixA[2][0]);

        //mb3k1
        minor[2][0] = (matrixA[0][1] * matrixA[1][2]) - (matrixA[0][2] * matrixA[1][1]);
        //mb3k2
        minor[2][1] = (matrixA[0][0] * matrixA[1][2]) - (matrixA[0][2] * matrixA[1][0]);
        //mb2k3
        minor[2][2] = (matrixA[0][0] * matrixA[1][1]) - (matrixA[0][1] * matrixA[1][0]);

    }

    public void kofaktor() {
        Minor();
        kofaktor[0][0] = 1 * minor[0][0];
        kofaktor[0][1] = -1 * minor[0][1];
        kofaktor[0][2] = 1 * minor[0][2];
        kofaktor[1][0] = -1 * minor[1][0];
        kofaktor[1][1] = 1 * minor[1][1];
        kofaktor[1][2] = -1 * minor[1][2];
        kofaktor[2][0] = 1 * minor[2][0];
        kofaktor[2][1] = -1 * minor[2][1];
        kofaktor[2][2] = 1 * minor[2][2];

    }

    public void adjoin() {
        kofaktor();
        double determinan = 1 / determinan();
        adjoin[0][0] = determinan * kofaktor[0][0];
        adjoin[0][1] = determinan * kofaktor[0][1];
        adjoin[0][2] = determinan * kofaktor[0][2];
        adjoin[1][0] = determinan * kofaktor[1][0];
        adjoin[1][1] = determinan * kofaktor[1][1];
        adjoin[1][2] = determinan * kofaktor[1][2];
        adjoin[2][0] = determinan * kofaktor[2][0];
        adjoin[2][1] = determinan * kofaktor[2][1];
        adjoin[2][2] = determinan * kofaktor[2][2];
        
        // render menjadi pecahan/fraction
        pecahan[0][0] = new Fraction(adjoin[0][0]);
        pecahan[0][1] = new Fraction(adjoin[0][1]);
        pecahan[0][2] = new Fraction(adjoin[0][2]);
        pecahan[1][0] = new Fraction(adjoin[1][0]);
        pecahan[1][1] = new Fraction(adjoin[1][1]);
        pecahan[1][2] = new Fraction(adjoin[1][2]);
        pecahan[2][0] = new Fraction(adjoin[2][0]);
        pecahan[2][1] = new Fraction(adjoin[2][1]);
        pecahan[2][2] = new Fraction(adjoin[2][2]);
    
        b1k1hasil.setText(String.valueOf(pecahan[0][0]));
        b2k1hasil.setText(String.valueOf(pecahan[0][1]));
        b3k1hasil.setText(String.valueOf(pecahan[0][2]));
        b1k2hasil.setText(String.valueOf(pecahan[1][0]));
        b2k2hasil.setText(String.valueOf(pecahan[1][1]));
        b3k2hasil.setText(String.valueOf(pecahan[1][2]));
        b1k3hasil.setText(String.valueOf(pecahan[2][0]));
        b2k3hasil.setText(String.valueOf(pecahan[2][1]));
        b3k3hasil.setText(String.valueOf(pecahan[2][2]));
    }

  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OBE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OBE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1k1a;
    private javax.swing.JTextField b1k1hasil;
    private javax.swing.JTextField b1k2a;
    private javax.swing.JTextField b1k2hasil;
    private javax.swing.JTextField b1k3a;
    private javax.swing.JTextField b1k3hasil;
    private javax.swing.JTextField b2k1a;
    private javax.swing.JTextField b2k1hasil;
    private javax.swing.JTextField b2k2a;
    private javax.swing.JTextField b2k2hasil;
    private javax.swing.JTextField b2k3a;
    private javax.swing.JTextField b2k3hasil;
    private javax.swing.JTextField b3k1a;
    private javax.swing.JTextField b3k1hasil;
    private javax.swing.JTextField b3k2a;
    private javax.swing.JTextField b3k2hasil;
    private javax.swing.JTextField b3k3a;
    private javax.swing.JTextField b3k3hasil;
    private javax.swing.JButton hasil;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
